### ISSUE TITLE
人人簽到又無法使用了

### ISSUE THREAD

**Issue by NeiL978** [Friday21/auto_sign-python3#3]
現在執行會跑出這個訊息，是我設定問題還是什麼問題呢？
`Traceback (most recent call last):
  File "/Users/NeiL_MBP/Documents/crontab/zimuzu.py", line 83, in <module>
    if sign('XXX@gmail.com', 'XXX'):
  File "/Users/NeiL_MBP/Documents/crontab/zimuzu.py", line 61, in sign
    data = json.loads(data.decode('utf-8'))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by Friday21** [comment]
貌似人人影视网页做了改变导致解码不正确， 我看看怎么修改

**Comment by NeiL978** [comment]
好的 麻煩你了

**Comment by Friday21** [comment]
貌似又能用了。。。
